version: '3'
services:
  evcc:
    image: stefanschoof/evcc:virtualid
    container_name: evcc
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - ./evcc-tmpl.yaml:/etc/evcc-tmpl.yaml
    ports:
    - 7070:7070
    networks:
    - traefik
    command: /bin/sh -c "sed -e \"s/<vin>/$vin/\" -e \"s/<mail>/$mail/\" -e \"s/<password>/$password/\" -e \"s#<influxurl>#$influxurl#\" -e \"s/<influxtoken>/$influxtoken/\" /etc/evcc-tmpl.yaml > /etc/evcc.yaml && evcc"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.evcc.loadbalancer.server.port=7070"
      - "com.centurylinklabs.watchtower.monitor-only=true"

networks:
  traefik:
    external: true
