version: '3'
services:

  evcc:
    image: stefanschoof/evcc:virtualid
    env_file:
    - .env
    volumes:
      - ./evcc-tmpl.yaml:/etc/evcc-tmpl.yaml
    ports:
    - 7070:7070
    networks:
    - evcc
    command: /bin/sh -c "sed -e \"s/<vin>/$vin/\" -e \"s/<mail>/$mail/\" -e \"s/<password>/$password/\" -e \"s#<influxurl>#$influxurl#\" -e \"s/<influxtoken>/$influxtoken/\" /etc/evcc-tmpl.yaml > /etc/evcc.yaml && evcc"
    restart: always
networks:
  evcc:
